#include <iostream>
#include <vector>
#include <discretex/discretex.hpp>

int main() {
    std::cout << "=== DiscreteX Example: Normal Subgroups and First Isomorphism Theorem ===\n";

    using namespace discretex;
    using namespace discretex::algebra;

    // 1. Construct non-abelian symmetric group S_3 (order 6)
    // Permutations of {0, 1, 2}:
    std::vector<std::vector<std::size_t>> perms = {
        {0, 1, 2}, // 0: (1) Identity
        {1, 2, 0}, // 1: (0 1 2) 3-cycle
        {2, 0, 1}, // 2: (0 2 1) 3-cycle
        {0, 2, 1}, // 3: (1 2) transposition
        {2, 1, 0}, // 4: (0 2) transposition
        {1, 0, 2}  // 5: (0 1) transposition
    };

    auto s3_op = operation_table<index_domain>::from_callable(
        index_domain(6),
        [&](std::size_t i, std::size_t j) {
            std::vector<std::size_t> comp = {
                perms[i][perms[j][0]],
                perms[i][perms[j][1]],
                perms[i][perms[j][2]]
            };
            for (std::size_t k = 0; k < 6; ++k) {
                if (perms[k] == comp) return k;
            }
            return 6UL;
        });

    finite_group<index_domain> s3(index_domain(6), std::move(s3_op));
    std::cout << "1. Group S_3 constructed (order = " << s3.order() << ", abelian = " << (s3.is_abelian() ? "true" : "false") << ")\n";

    // 2. Normal Subgroup: Alternating group A_3 = {0, 1, 2}
    std::vector<std::size_t> A3 = {0, 1, 2};
    bool a3_normal = is_normal_subgroup(s3, A3);
    std::cout << "2. Subgroup A_3 = {0, 1, 2} normal in S_3: " << (a3_normal ? "YES" : "NO") << "\n";

    // Non-normal subgroup H_trans = {0, 3}
    std::vector<std::size_t> H_trans = {0, 3};
    bool h_normal = is_normal_subgroup(s3, H_trans);
    std::cout << "   Subgroup H = {0, 3} (generated by transposition) normal in S_3: " << (h_normal ? "YES" : "NO") << "\n";

    // 3. Construct Quotient Group S_3 / A_3
    auto q_res = quotient_group(s3, A3);
    std::cout << "3. Quotient Group S_3 / A_3 constructed with order " << q_res.quotient.order() << "\n";
    for (std::size_t c = 0; c < q_res.cosets.size(); ++c) {
        std::cout << "     Coset " << c << ": { ";
        for (std::size_t elem : q_res.cosets[c]) std::cout << elem << " ";
        std::cout << "}\n";
    }

    // 4. Parity homomorphism f: S_3 -> Z_2
    // Even permutations map to 0, odd permutations map to 1
    auto z2 = cyclic_group(2);
    std::vector<std::size_t> sgn_map = {0, 0, 0, 1, 1, 1};

    // 5. Certify the First Isomorphism Theorem: S_3 / ker(f) =~ im(f)
    auto cert = certify_first_isomorphism_theorem(s3, z2, sgn_map);
    std::cout << "4. First Isomorphism Theorem S_3 / A_3 =~ Z_2: " << (cert.is_valid_isomorphism ? "CERTIFIED" : "FAILED") << "\n";

    return 0;
}
